name: CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  lint:
    name: Code linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 18.x
          cache: yarn
      - run: yarn --frozen-lockfile
      - run: yarn lint
      - run: yarn test
