name: deploy
on:
  push:
    branches: [main]
    tags: [v*]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build (e.g., PR branch)'
        required: true
        default: 'main'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Metadata
        id: meta_services
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          labels: |
            org.opencontainers.image.licenses=GPL-3.0-or-later

      - name: Image build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta_services.outputs.tags }}
          labels: ${{ steps.meta_services.outputs.labels }}
